apiVersion: dns-ingress.io/v1alpha1
kind: Domain
metadata:
  labels:
    app.kubernetes.io/name: domain
    app.kubernetes.io/instance: domain-sample
    app.kubernetes.io/part-of: dns-ingress
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dns-ingress
  name: domain-sample
spec:
  # TODO(user): Add fields here
